name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: test-react-app

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install
#    - run: npm run build
#    - run: npm test

    - name: ▶️ Run setup script
      run: npm run setup  

    - name: ▶️ Copy to document root
      run: cp -r ~/test-react-app/work/testing-react-apps/testing-react-apps /var/

    - name: ▶️ chown
      run: sudo chown ubuntu:ubuntu /var/testing-react-apps

    - name: ▶️ run docker-compose up
      run: cd /var/testing-react-apps && docker-compose up -d
